name: 貢獻者清單產生

on:
  push:
    branches:
    - "main"
  workflow_dispatch: {}

jobs:
  contrib-readme-job:
    name: 貢獻者清單
    uses: TeamKugimiya/reusable-workflows/.github/workflows/Contributors.yml@main
