#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""掃 .github/workflows/*.yml 產出 docs/<name>.md 與 README 索引段落。

慣例：
  workflow yml 開頭以 comment 提供 metadata：
      # summary: 一句話描述
      # category: 分類名稱

  README 的索引區塊以下列 marker 包夾，整段會被覆寫：
      <!-- workflows:start -->
      ...
      <!-- workflows:end -->

用法：
  python scripts/gen_workflow_docs.py          # 產生 / 更新
  python scripts/gen_workflow_docs.py --check  # CI：diff 不為零則 exit 1
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS_DIR = ROOT / ".github" / "workflows"
DOCS_DIR = ROOT / "docs"
README = ROOT / "README.md"
MARKER_START = "<!-- workflows:start -->"
MARKER_END = "<!-- workflows:end -->"

META_RE = re.compile(r"^#\s*(summary|category)\s*:\s*(.+?)\s*$", re.IGNORECASE)


def parse_meta(text: str) -> dict[str, str]:
    meta: dict[str, str] = {}
    for line in text.splitlines():
        if not line.startswith("#"):
            if line.strip() and not line.startswith("#"):
                break
        m = META_RE.match(line)
        if m:
            meta[m.group(1).lower()] = m.group(2)
    return meta


def load_workflows() -> list[dict[str, Any]]:
    out = []
    for path in sorted(WORKFLOWS_DIR.glob("*.yml")):
        if path.name.startswith("_"):
            continue
        text = path.read_text(encoding="utf-8")
        data = yaml.safe_load(text) or {}
        # PyYAML 把裸 `on:` 解析成 True
        on = data.get("on") or data.get(True) or {}
        if "workflow_call" not in on:
            continue
        meta = parse_meta(text)
        out.append(
            {
                "path": path,
                "filename": path.name,
                "stem": path.stem,
                "name": data.get("name", path.stem),
                "summary": meta.get("summary", ""),
                "category": meta.get("category", "未分類"),
                "inputs": (on["workflow_call"] or {}).get("inputs") or {},
                "secrets": (on["workflow_call"] or {}).get("secrets") or {},
                "outputs": (on["workflow_call"] or {}).get("outputs") or {},
                "permissions": data.get("permissions") or {},
            }
        )
    return out


GENERATED_MARKER = "<!-- generated by scripts/gen_workflow_docs.py -->"


def render_doc(wf: dict[str, Any]) -> str:
    lines = [
        GENERATED_MARKER,
        "",
        f"# {wf['name']}",
        "",
        wf["summary"] or "_（尚未提供 summary）_",
        "",
        f"- **檔案**：[`.github/workflows/{wf['filename']}`](../.github/workflows/{wf['filename']})",
        f"- **分類**：{wf['category']}",
        "",
        "## Inputs",
        "",
    ]
    if wf["inputs"]:
        lines += [
            "| 名稱 | 型別 | 必填 | 預設 | 說明 |",
            "| --- | --- | --- | --- | --- |",
        ]
        for key, spec in wf["inputs"].items():
            spec = spec or {}
            raw_default = spec.get("default", "")
            if isinstance(raw_default, bool):
                default = f"`{str(raw_default).lower()}`"
            elif raw_default == "" or raw_default is None:
                default = "—"
            else:
                default = f"`{raw_default}`"
            required = "✅" if spec.get("required") else "—"
            lines.append(
                f"| `{key}` | `{spec.get('type', '')}` | {required} | {default} | {spec.get('description', '').strip()} |"
            )
    else:
        lines.append("_無_")
    lines += ["", "## Outputs", ""]
    if wf["outputs"]:
        lines += ["| 名稱 | 說明 |", "| --- | --- |"]
        for key, spec in wf["outputs"].items():
            spec = spec or {}
            lines.append(f"| `{key}` | {spec.get('description', '').strip()} |")
    else:
        lines.append("_無_")
    lines += ["", "## Secrets", ""]
    if wf["secrets"]:
        lines += ["| 名稱 | 必填 | 說明 |", "| --- | --- | --- |"]
        for key, spec in wf["secrets"].items():
            spec = spec or {}
            required = "✅" if spec.get("required") else "—"
            lines.append(
                f"| `{key}` | {required} | {spec.get('description', '').strip()} |"
            )
    else:
        lines.append("_無_")
    lines += [
        "",
        "## 使用範例",
        "",
        "```yaml",
        "jobs:",
        "  call:",
        f"    uses: TeamKugimiya/reusable-workflows/.github/workflows/{wf['filename']}@v1",
        "    with:",
    ]
    required_inputs = [k for k, v in wf["inputs"].items() if (v or {}).get("required")]
    for key in required_inputs or list(wf["inputs"].keys())[:1]:
        lines.append(f"      {key}: <值>")
    if wf["secrets"]:
        lines.append("    secrets:")
        for key in wf["secrets"].keys():
            lines.append(f"      {key}: ${{{{ secrets.{key.upper()} }}}}")
    lines += ["```", ""]
    if wf["secrets"]:
        lines += [
            "> 上例使用顯式傳遞，需在呼叫端 repo 的 *Settings → Secrets and variables → Actions* 建立同名 secret。",
            "> 若呼叫端與被呼叫端在同 organization 且已設定 organization secret，也可改寫成 `secrets: inherit` 一次帶入全部。",
            "",
        ]
    return "\n".join(lines)


def render_index(workflows: list[dict[str, Any]]) -> str:
    by_cat: dict[str, list[dict[str, Any]]] = {}
    for wf in workflows:
        by_cat.setdefault(wf["category"], []).append(wf)
    lines = [MARKER_START, ""]
    for cat in sorted(by_cat.keys()):
        lines.append(f"### {cat}")
        lines.append("")
        lines.append("| 工作流程 | 用途 |")
        lines.append("| --- | --- |")
        for wf in by_cat[cat]:
            lines.append(
                f"| [{wf['name']}](docs/{wf['stem']}.md) | {wf['summary']} |"
            )
        lines.append("")
    lines.append(MARKER_END)
    return "\n".join(lines)


def update_readme(index_block: str) -> str:
    text = README.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END), re.DOTALL
    )
    if pattern.search(text):
        return pattern.sub(index_block, text)
    # 找不到 marker → 附加在「## 可用工作流程」後或檔尾
    return text.rstrip() + "\n\n" + index_block + "\n"


def write(path: Path, content: str, files: list[Path]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8")
    files.append(path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="CI 檢查，diff 不為零則 fail")
    args = parser.parse_args()

    workflows = load_workflows()
    touched: list[Path] = []

    DOCS_DIR.mkdir(exist_ok=True)
    for wf in workflows:
        write(DOCS_DIR / f"{wf['stem']}.md", render_doc(wf), touched)

    new_readme = update_readme(render_index(workflows))
    write(README, new_readme, touched)

    # 清理 docs/ 中已不存在的 workflow 對應檔（僅刪除自動產生的）
    keep = {f"{wf['stem']}.md" for wf in workflows}
    for md in DOCS_DIR.glob("*.md"):
        if md.name in keep:
            continue
        try:
            head = md.read_text(encoding="utf-8").lstrip().splitlines()[0]
        except (OSError, IndexError):
            continue
        if head.strip() == GENERATED_MARKER:
            md.unlink()

    if args.check:
        result = subprocess.run(
            ["git", "diff", "--exit-code", "--", "docs/", "README.md"],
            cwd=ROOT,
        )
        if result.returncode != 0:
            print(
                "docs/ 或 README.md 與 workflow 定義不同步，請於本機執行 "
                "`python scripts/gen_workflow_docs.py` 後提交。",
                file=sys.stderr,
            )
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
