name: 模組包 - 補丁

on:
  workflow_call:
    inputs:
      modpack-name:
        required: true
        type: string
      modpack-version:
        required: true
        type: string
      modpack-resourcepack:
        required: true
        type: string

jobs:
  Patcher:
    name: 製作補丁
    runs-on: ubuntu-latest

    steps:
      - name: 查看專案
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 下載 reusable workflow 到資料夾
        uses: actions/checkout@v3
        with:
          repository: TeamKugimiya/reusable-workflows
          path: reusable-workflow-repo

      - name: 下載補丁資源包
        if: ${{ inputs.modpack-resourcepack == 'true' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.modpack-name }}-Patches-Resourcepack
          path: ./resourcepacks/

      - name: 製作補丁
        run: ./reusable-workflow-repo/patch-maker.sh
        env:
          version: ${{ inputs.modpack-version }}

      - name: 上傳補丁
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.modpack-name }}-Patches
          path: "*.zip"
