name: 模組包 - 模組包資源包補丁

on:
  workflow_call:
    inputs:
      modpack-name:
        required: true
        type: string
      resourcepack-generate:
        required: true
        type: string

jobs:
  ResourcePack:
    name: 製作資源包補丁
    if: ${{ inputs.resourcepack-generate == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: 查看專案
        uses: actions/checkout@v3
        with:
          ref: resourcepack
          fetch-depth: 0

      - name: 優化資源包
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          never_store_squash_times: true
          path: ./

      - name: 下載優化資源包成品
        uses: actions/download-artifact@v3
        with:
          name: Optimized pack
          path: ./

      - name: 刪除優化資源包成品
        uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            Optimized pack

      - name: 重新命名資源包
        run: |
          mv ./pack.zip ${{ inputs.modpack-name }}-Patches.zip

      - name: 上傳資源包
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.modpack-name }}-Patches-Resourcepack
          path: "*.zip"
