name: 模組包 - 環境變數設定

on:
  workflow_call:
    outputs:
      modpack-name:
        description: "模組包名稱"
        value: ${{ jobs.Environment-Setup.outputs.modpack_name }}
      resourcepack-patch-generate:
        description: "是否生成「模組包資源包補丁」"
        value: ${{ jobs.Environment-Setup.outputs.resourcepack_patch_generate }}
      server_patch_generate:
        description: "是否生成「伺服器補丁」"
        value: ${{ jobs.Environment-Setup.outputs.server_patch_generate }}

jobs:
  Environment-Setup:
    name: 設置環境變數
    runs-on: ubuntu-latest

    outputs:
      modpack_name: ${{ steps.env_setup.outputs.out_modpack_name }}
      resourcepack_patch_generate: ${{ steps.env_setup.outputs.out_resourcepack_patch_generate }}
      server_patch_generate: ${{ steps.env_setup.outputs.out_server_patch_generate }}

    steps:
      - name: 查看專案
        uses: actions/checkout@v3

      - name: 下載 reusable workflow 到資料夾
        uses: actions/checkout@v3
        with:
          repository: TeamKugimiya/reusable-workflows
          path: reusable-workflow-repo

      - name: 設定環境變數
        id: env_setup
        run: ./reusable-workflow-repo/environment-setup.sh
