name: 模組包 - 發布

on:
  workflow_call:
    inputs:
      modpack-name:
        required: true
        type: string
      modpack-version:
        required: true
        type: string
      modpack-official-version:
        required: true
        type: string
      modpack-per-release:
        required: true
        type: string
      modpack-release-ignore:
        required: false
        type: string
        default: "false"
      release-body-path:
        required: false
        type: string
        default: ".github/configs/release_body.md"

jobs:
  Release:
    name: 發布版本
    if: ${{ inputs.modpack-release-ignore != 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: 查看專案
        uses: actions/checkout@v3

      - name: 變數替換
        run: |
          sed -i 's/$ModPack_Name_VAR/${{ inputs.modpack-name }}/g' ${{ inputs.release-body-path }}
          sed -i 's/$ModPack_Version_VAR/${{ inputs.modpack-official-version }}/g' ${{ inputs.release-body-path }}

      - name: 下載補丁成品
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.modpack-name }}-Patches

      - name: 清理所有工作流程成品
        uses: geekyeggo/delete-artifact@v2
        with:
          name: ${{ inputs.modpack-name }}-*

      - name: 移動所有壓縮檔到主工作資料夾
        run: |
          ls -alh

      - name: 創建發布
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.modpack-name }} 中文化翻譯 ${{ inputs.modpack-version }}
          tag_name: ${{ inputs.modpack-version }}
          prerelease: ${{ inputs.modpack-per-release }}
          files: "*.zip"
          body_path: ${{ inputs.release-body-path }}
