name: "Testing ParaTranz Workflow"

on:
  workflow_call:
    inputs:
      paratranz_project_id:
        required: true
        type: string
    secrets:
      paratranz_token:
        required: true

env:
  python_version: "3.12"
  reusable_workflows_ref: ci/para
  poetry_installation_cache_key: poetry_cache_01
  LOGURU_LEVEL: "INFO"

jobs:
  para_cache:
    name: ParaTranz - Cache
    runs-on: ubuntu-latest
    outputs:
      cache_hit: ${{ steps.para_cache.outputs.cache-hit }}
    steps:
      ### Checkout Main and Reusable Workflows ###
      - name: Checkout Repository - Main
        uses: actions/checkout@v4

      - name: Checkout Repository - Reusable Workflows
        uses: actions/checkout@v4
        with:
          repository: TeamKugimiya/reusable-workflows
          ref: ${{ env.reusable_workflows_ref }}
          path: .github/reusable-workflows

      ### Setup script dependencies ###
      - name: Setup - Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}

      - name: Setup - Move Poetry Project Files
        run: |
          cp .github/reusable-workflows/pyproject.toml .
          cp .github/reusable-workflows/poetry.lock .

      - name: Cache - Poetry Installation
        id: poetry_installation_cache
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ env.poetry_installation_cache_key }}

      - name: Setup - Poetry Install
        if: ${{ steps.poetry_installation_cache.outputs.cache-hit != 'true' }}
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Cache - Poetry Dependencies
        id: poetry_dependencies_cache
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Setup - Poetry install dependencies
        if: ${{ steps.poetry_dependencies_cache.outputs.cache-hit != 'true' }}
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
          poetry install --no-interaction

      ### Start Script ###
      - name: ParaTranz - Cache
        env:
          PROJECT_ID: ${{ inputs.paratranz_project_id }}
          API_TOKEN: ${{ secrets.paratranz_token }}
        run: |
          poetry run python $GITHUB_WORKSPACE/.github/reusable-workflows/para-scripts/00_paratranz_cache.py

      - name: Cache - ParaTranz
        id: para_cache
        uses: actions/cache@v4
        with:
          path: .cache/paratranz_cache.txt
          key: paratranz_cache-${{ hashFiles('.cache/paratranz_cache.txt') }}

  para_summary:
    name: ParaTranz - Summary
    runs-on: ubuntu-latest
    needs: [ para_cache ]
    if: ${{ needs.para_cache.outputs.cache_hit != 'true' }}
    steps:
      ### Checkout Main and Reusable Workflows ###
      - name: Checkout Repository - Main
        uses: actions/checkout@v4

      - name: Checkout Repository - Reusable Workflows
        uses: actions/checkout@v4
        with:
          repository: TeamKugimiya/reusable-workflows
          ref: ${{ env.reusable_workflows_ref }}
          path: .github/reusable-workflows

      ### Setup script dependencies ###
      - name: Setup - Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}

      - name: Setup - Move Poetry Project Files
        run: |
          cp .github/reusable-workflows/pyproject.toml .
          cp .github/reusable-workflows/poetry.lock .

      - name: Cache - Poetry Installation
        id: poetry_installation_cache
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ env.poetry_installation_cache_key }}

      - name: Setup - Poetry Install
        if: ${{ steps.poetry_installation_cache.outputs.cache-hit != 'true' }}
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Cache - Poetry Dependencies
        id: poetry_dependencies_cache
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Setup - Poetry install dependencies
        if: ${{ steps.poetry_dependencies_cache.outputs.cache-hit != 'true' }}
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
          poetry install --no-interaction

      ### Start Script ###
      - name: ParaTranz - Generate Summary
        env:
          PROJECT_ID: ${{ inputs.paratranz_project_id }}
          API_TOKEN: ${{ secrets.paratranz_token }}
        run: |
          poetry run python $GITHUB_WORKSPACE/.github/reusable-workflows/para-scripts/01_paratranz_summary.py

  para_paraify:
    name: ParaTranz - Paraify
    runs-on: ubuntu-latest
    needs: [ para_cache ]
    if: ${{ needs.para_cache.outputs.cache_hit != 'true' }}
    steps:
      ### Checkout Main and Reusable Workflows ###
      - name: Checkout Repository - Main
        uses: actions/checkout@v4

      - name: Checkout Repository - Reusable Workflows
        uses: actions/checkout@v4
        with:
          repository: TeamKugimiya/reusable-workflows
          ref: ${{ env.reusable_workflows_ref }}
          path: .github/reusable-workflows

      ### Setup script dependencies ###
      - name: Setup - Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}

      - name: Setup - Move Poetry Project Files
        run: |
          cp .github/reusable-workflows/pyproject.toml .
          cp .github/reusable-workflows/poetry.lock .

      - name: Cache - Poetry Installation
        id: poetry_installation_cache
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ env.poetry_installation_cache_key }}

      - name: Setup - Poetry Install
        if: ${{ steps.poetry_installation_cache.outputs.cache-hit != 'true' }}
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Cache - Poetry Dependencies
        id: poetry_dependencies_cache
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Setup - Poetry install dependencies
        if: ${{ steps.poetry_dependencies_cache.outputs.cache-hit != 'true' }}
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
          poetry install --no-interaction

      ### Start Script ###
      - name: ParaTranz - Download Artifact
        env:
          PROJECT_ID: ${{ inputs.paratranz_project_id }}
          API_TOKEN: ${{ secrets.paratranz_token }}
        run: |
          poetry run python $GITHUB_WORKSPACE/.github/reusable-workflows/para-scripts/02_paratranz_download.py

      - name: ParaTranz - Extract Artifact
        run: |
          poetry run python $GITHUB_WORKSPACE/.github/reusable-workflows/para-scripts/03_paratranz_extract.py

      - name: ParaTranz - Minecraft Language JSON & Structure
        run: |
          poetry run python $GITHUB_WORKSPACE/.github/reusable-workflows/para-scripts/04_paratranz_language.py

      - name: Cache - Files Hash
        uses: actions/cache@v4
        with:
          path: .cache/paratranz_files_cache.json
          key: paratranz_files_cache-${{ hashFiles('.cache/paratranz_files_cache.json') }}
          restore-keys: paratranz_files_cache-

      - name: ParaTranz - Date Fixer
        env:
          PROJECT_ID: ${{ inputs.paratranz_project_id }}
          API_TOKEN: ${{ secrets.paratranz_token }}
        run: |
          poetry run python $GITHUB_WORKSPACE/.github/reusable-workflows/para-scripts/05_paratranz_datefixer.py

      - name: GitHub - Upload Translate Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ParaTranslateSource
          path: .workdir/MultiVersions
          compression-level: 9

  para_matrix:
    name: GitHub - Matrix Setup
    runs-on: ubuntu-latest
    needs: [ para_paraify ]
    outputs:
      matrix_json: ${{ steps.gh_matrix.outputs.matrix_json }}
    steps:
      ### Checkout Main and Reusable Workflows ###
      - name: Checkout Repository - Main
        uses: actions/checkout@v4

      - name: Checkout Repository - Reusable Workflows
        uses: actions/checkout@v4
        with:
          repository: TeamKugimiya/reusable-workflows
          ref: ${{ env.reusable_workflows_ref }}
          path: .github/reusable-workflows

      ### Setup script dependencies ###
      - name: Setup - Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}

      - name: Setup - Move Poetry Project Files
        run: |
          cp .github/reusable-workflows/pyproject.toml .
          cp .github/reusable-workflows/poetry.lock .

      - name: Cache - Poetry Installation
        id: poetry_installation_cache
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ env.poetry_installation_cache_key }}

      - name: Setup - Poetry Install
        if: ${{ steps.poetry_installation_cache.outputs.cache-hit != 'true' }}
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Cache - Poetry Dependencies
        id: poetry_dependencies_cache
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Setup - Poetry install dependencies
        if: ${{ steps.poetry_dependencies_cache.outputs.cache-hit != 'true' }}
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
          poetry install --no-interaction

      ### Start Script ###
      - name: Poetry - Setup Matrix Json
        id: gh_matrix
        run: |
          poetry run python $GITHUB_WORKSPACE/.github/reusable-workflows/para-scripts/06_github_matrix.py

  para_packer:
    name: ParaTranz - PackUp ${{ matrix.mc_version }}
    runs-on: ubuntu-latest
    needs: [ para_matrix ]
    strategy:
      matrix: ${{ fromJson(needs.para_matrix.outputs.matrix_json) }}
    steps:
      ### Checkout Main and Reusable Workflows ###
      # - name: Checkout Repository - Main
      #   uses: actions/checkout@v4
      - name: Checkout Repository - Initialize
        run: |
          git init

      - name: Checkout Repository - Reusable Workflows
        uses: actions/checkout@v4
        with:
          repository: TeamKugimiya/reusable-workflows
          ref: ${{ env.reusable_workflows_ref }}
          path: .github/reusable-workflows

      ### Setup script dependencies ###
      - name: Setup - Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}

      - name: Setup - Move Poetry Project Files
        run: |
          cp .github/reusable-workflows/pyproject.toml .
          cp .github/reusable-workflows/poetry.lock .

      - name: Cache - Poetry Installation
        id: poetry_installation_cache
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ env.poetry_installation_cache_key }}

      - name: Setup - Poetry Install
        if: ${{ steps.poetry_installation_cache.outputs.cache-hit != 'true' }}
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Cache - Poetry Dependencies
        id: poetry_dependencies_cache
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Setup - Poetry install dependencies
        if: ${{ steps.poetry_dependencies_cache.outputs.cache-hit != 'true' }}
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
          poetry install --no-interaction

      ### Start Script ###
      - name: GitHub - Download Translate Artifact
        uses: actions/download-artifact@v4
        with:
          name: ParaTranslateSource
          path: MultiVersions

      - name: Packer - Generate Mcmeta
        env:
          mc_pack_format: ${{ matrix.mc_pack_format }}
          mc_supported_formats_min: ${{ matrix.mc_supported_formats_min }}
          mc_supported_formats_max: ${{ matrix.mc_supported_formats_max }}
        run: |
          poetry run python $GITHUB_WORKSPACE/.github/reusable-workflows/para-scripts/07_github_pack_meta.py

      ### Current we only have main folder, don't have multiversion
      - name: Packer Tempoary - Move files
        run: |
          mv MultiVersions/Forge/main/* pack/assets/

      - name: Packer - PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest-unstable
          artifact_name: ParaTranslationPack-${{ matrix.mc_version }}
          options: |
            pack_directory = 'pack'
