name: 同步分支資料夾

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
        description: "分支名稱"
      path:
        required: true
        type: string
        description: "資料夾路徑，所設定的資料夾內的所有資料將會被轉移到該分支下的根目錄"
      license_inculde:
        required: false
        type: boolean
        description: "是否自動複製授權許可文件"
      license_path:
        required: false
        type: string
        default: "LICENSE"
        description: "授權許可文件的路徑，預設為 ``LICENSE``"

jobs:
  Sync:
    name: 同步流程
    runs-on: ubuntu-latest

    steps:
      - name: 查看專案 (主要)
        uses: actions/checkout@v3

      - name: 查看專案 (次要)
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch_name }}
          path: action-${{ inputs.branch_name }}

      - name: 複製資料夾內容
        run: |
          shopt -u dotglob
          rm -rv action-${{ inputs.branch_name }}/*
          cp -r ${{ inputs.path }}/* action-${{ inputs.branch_name }}

      - name: 授權條款複製
        if: ${{ inputs.license_inculde }}
        run: |
          cp -r ${{ inputs.license_path }} action-${{ inputs.branch_name }}
      
      - name: Git SHA
        id: git_version
        run: |
          echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
 
      - name: 提交同步內容
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './action-${{ inputs.branch_name }}'
          default_author: github_actions
          message: "ci(sync): 自動同步資料夾 ${{ steps.git_version.outputs.sha }}"
